"""Conan recipe for gorden + roboslop.

Pulls Conan-Center dependencies only. bgfx (+ bx, bimg, shaderc), miniaudio,
and imgui_impl_bgfx are vendored under third_party/ — see
docs/todo/open-questions.md item 5.

Build flow:
    conan install . --output-folder=build/<preset> --profile=conan/profiles/<x>
    cmake --preset <preset>
    cmake --build --preset <preset>

CMakeUserPresets.json is auto-generated by Conan and gitignored; our hand-
written CMakePresets.json is the source of truth for preset definitions.
"""

from conan import ConanFile
from conan.tools.cmake import CMakeDeps, CMakeToolchain


class Gorden(ConanFile):
    name = "gorden"
    version = "0.0.1"
    settings = "os", "compiler", "build_type", "arch"

    def requirements(self):
        # Windowing, ECS, math, logging, formatting, serialisation.
        self.requires("glfw/3.4")
        self.requires("entt/3.13.2")
        self.requires("glm/1.0.1")
        self.requires("spdlog/1.14.1")
        self.requires("fmt/10.2.1", override=True)
        self.requires("nlohmann_json/3.11.3")

        # Testing.
        self.requires("catch2/3.6.0")

        # Asset import, physics, image loading.
        self.requires("assimp/5.4.2")
        # Match the version assimp 5.4.2 transitively requires.
        self.requires("stb/cci.20230920")
        self.requires("joltphysics/5.2.0")

        # Dev UI. Docking branch — see docs/todo/open-questions.md item 8.
        self.requires("imgui/1.90.8-docking")

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        # Honour the generator declared by the profile (Ninja); never let Conan
        # silently pick Make.
        tc.generate()
