"""Conan recipe for roboslop (engine + apps).

Pulls Conan-Center dependencies only. bgfx (+ bx, bimg, shaderc), miniaudio,
and imgui_impl_bgfx are vendored under third_party/ — see
docs/build-system.md for the dependency-strategy decision tree.

Build flow:
    conan install . --output-folder=build/<preset> --profile=conan/profiles/<x>
    cmake --preset <preset>
    cmake --build --preset <preset>

CMakeUserPresets.json is auto-generated by Conan and gitignored; our hand-
written CMakePresets.json is the source of truth for preset definitions.
"""

from conan import ConanFile
from conan.tools.cmake import CMakeDeps, CMakeToolchain


class Roboslop(ConanFile):
    name = "roboslop"
    version = "0.0.1"
    settings = "os", "compiler", "build_type", "arch"

    def configure(self):
        # Build glfw with both Linux backends. The recipe defaults to X11
        # only; with_wayland pulls in wayland (shared), xkbcommon with its
        # Wayland support, and wayland-protocols as a tool requirement.
        # GLFW picks the platform at runtime (Wayland when WAYLAND_DISPLAY
        # is set, X11 otherwise), so one package serves both sessions.
        if self.settings.os == "Linux":
            self.options["glfw"].with_wayland = True

    def requirements(self):
        # Windowing, ECS, math, logging, formatting, serialisation.
        self.requires("glfw/3.4")
        self.requires("entt/3.13.2")
        self.requires("glm/1.0.1")
        self.requires("spdlog/1.14.1")
        self.requires("fmt/10.2.1", override=True)
        self.requires("nlohmann_json/3.11.3")

        # Testing.
        self.requires("catch2/3.6.0")

        # Asset import, physics, image loading.
        self.requires("assimp/5.4.2")
        # Match the version assimp 5.4.2 transitively requires.
        self.requires("stb/cci.20230920")
        self.requires("joltphysics/5.2.0")

        # System scheduling. Header-only task graph executor used by the
        # engine's SystemGraph / RenderGraph; one tf::Executor per App.
        self.requires("taskflow/3.7.0")

        # Dev UI. Docking branch for multi-viewport / dockable panels.
        self.requires("imgui/1.90.8-docking")

        # HTTP client for LLM backends (roboslop.platform.http). Default
        # options give OpenSSL-backed HTTPS on Linux; the first bootstrap
        # builds OpenSSL from source, which takes a few minutes.
        self.requires("libcurl/8.21.0")

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        # Honour the generator declared by the profile (Ninja); never let Conan
        # silently pick Make.
        tc.generate()
